### PR TITLE
Added spectrum splitting optimization, and other documentation cleanups

### PR DESCRIPTION
**Pull request by dsambit**

### CODE REVIEW

**Comment by dsambit** [comment]
After this PR is merged, we should create a new release tag. I am wondering whether it should be 0.5.1-pre or 0.6.0-pre as a new feature (spectrum splitting) is added. Alternatively I could delete the old 0.5.0-pre tag and create a fresh 0.5.0-pre tag.

**Review by phanimotamarri — APPROVED** [review]
Reviewed the PR in bitbucket and appropriately suggested few changes and has been incorporated!

**Comment by phanimotamarri** [comment]
Since this feature is in pre-release we can call 0.5.0-pre itself. We will follow x.y.z convention after the release tag!

**Comment by dsambit** [comment]
@phanimotamarri keeping it at 0.5.0-pre sounds good to me.

**Review by vikramgavini — APPROVED** [review]

**Pull request merged**
